import Head from "next/head";
import FormBody from "../components/FormBody";
import Header from "../components/Header";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nick Sakha Insurance</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Header />
      <FormBody />
    </div>
  );
}
